export const PATHS = {
  login: "/login",
  dashboard: "/",
  guests: "/guests",
  guestDetail: (id = ":id") => `/guests/${id}`,
  outlets: "/outlets",
  outletDetail: (id = ":id") => `/outlets/${id}`,
  rewards: "/rewards",
  rewardNew: "/rewards/new",
  rewardEdit: (id = ":id") => `/rewards/${id}/edit`,
  memberships: "/memberships",
  membershipNew: "/memberships/new",
  membershipEdit: (id = ":id") => `/memberships/${id}/edit`,
  campaigns: "/campaigns",
  campaignNew: "/campaigns/new",
  campaignEdit: (id = ":id") => `/campaigns/${id}/edit`,
  messages: "/messages",
  reviews: "/reviews",
  referrals: "/referrals",
  staff: "/staff",
  settings: "/settings",
} as const;
